/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/N5UdyaYsUQg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export default function Profile() {
  return (
    <div className="w-full max-w-md mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Edit Profile</h1>
          <p className="mt-2 text-muted-foreground">Update your personal information.</p>
        </div>
        <form className="space-y-6">
          <div className="grid gap-2">
            <Label htmlFor="name">Name</Label>
            <div className="flex items-center gap-2">
              <div className="text-muted-foreground">Current Name: John Doe</div>
              <Input id="name" type="text" defaultValue="John Doe" placeholder="Enter your name" />
            </div>
          </div>
          <Button type="submit" className="w-full">
            Save
          </Button>
        </form>
      </div>
    </div>
  )
}
